title: Fab Lab
description: Malware analysis and CTF writeup stuff
remote_theme: jekyll-theme-simplex
plugins:
  - jekyll-remote-theme

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  - 
    scope:
      path: ""
      type: category
    values:
      layout: "category"
